2nd Attempt
Error: Looks like you removed the element with a class of .tagline. You
will still need that, but will need to change it's element.

-I forgot to edit the id attibute.